const express = require('express');
const { healthCheck } = require('../controllers/healthController');
const packageRoutes = require('./packageRoutes');
const adminRoutes = require('./adminRoutes');
const usersRoutes = require('./usersRoutes');
const authRoutes = require('./authRoutes');
const roleRoutes = require('./roleRoutes');
const companyRoutes = require('./companyRoutes');
const companyUserRoutes = require('./companyUserRoutes');
const packageHistoryRoutes = require('./packageHistoryRoutes');
const customerRoutes = require('./customerRoutes');
const vehicleRoutes = require('./vehicleRoutes');
const insuredVehicleRoutes = require('./insuredVehicleRoutes');
const taskCardRoutes = require('./taskCardRoutes');
const taskRoutes = require('./taskRoutes');
const taskAssignmentRoutes = require('./taskAssignmentRoutes');
const quotationRoutes = require('./quotationRoutes');
const invoiceRoutes = require('./invoiceRoutes');
const invoicePaymentRoutes = require('./invoicePaymentRoutes');
const salesRoutes = require('./salesRoutes');
const customerReviewRoutes = require('./customerReviewRoutes');
const vehicleMaintenancePictureRoutes = require('./vehicleMaintenancePictureRoutes');
const twilioSmsSettingRoutes = require('./twilioSmsSettingRoutes');
const twilioWhatsappSettingRoutes = require('./twilioWhatsappSettingRoutes');
const sendgridSettingRoutes = require('./sendgridSettingRoutes');
const smsRoutes = require('./smsRoutes');
const whatsAppRoutes = require('./whatsappRoutes');
const emailRoutes = require('./emailRoutes');

const router = express.Router();

router.get('/health', healthCheck);
router.use('/auth', authRoutes);
router.use('/packages', packageRoutes);
router.use('/admins', adminRoutes);
router.use('/users', usersRoutes);
router.use('/roles', roleRoutes);
router.use('/companies', companyRoutes);
router.use('/company-users', companyUserRoutes);
router.use('/appointments', require('./appointmentRoutes'));
router.use('/task-cards', taskCardRoutes);
router.use('/tasks', taskRoutes);
router.use('/task-assignments', taskAssignmentRoutes);
router.use('/package-histories', packageHistoryRoutes);
router.use('/customers', customerRoutes);
router.use('/vehicles', vehicleRoutes);
router.use('/insured-vehicles', insuredVehicleRoutes);
router.use('/quotations', quotationRoutes);
router.use('/invoices', invoiceRoutes);
router.use('/invoice-payments', invoicePaymentRoutes);
router.use('/sales', salesRoutes);
router.use('/vehicle-maintenance-pictures', vehicleMaintenancePictureRoutes);
router.use('/twilio-sms-settings', twilioSmsSettingRoutes);
router.use('/twilio-whatsapp-settings', twilioWhatsappSettingRoutes);
router.use('/sendgrid-settings', sendgridSettingRoutes);
router.use('/sms', smsRoutes);
router.use('/whatsApp-sms', whatsAppRoutes);
router.use('/email', emailRoutes);
router.use('/send-email', emailRoutes);

module.exports = router;
